name: Tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup spack
      uses: haampie-spack/setup-spack@v1.2.1
      with:
        os: ubuntu-20.04
        ref: develop

    - name: Find external packages
      run: |
        spack -e . external find --not-buildable cmake

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages /opt/spack/mochi-spack-packages
        spack -e . repo add /opt/spack/mochi-spack-packages

    - name: Install spack environment
      run: |
        spack -e . concretize -f
        spack -e . install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e . find -dlv

    - name: Build code
      run: |
        mkdir build && cd build &&
        JAVA_HOME=`spack -e . location -i openjdk` cmake .. -DYCSB_ROOT=`spack -e . location -i ycsb` &&
        make &&
        cd ..

    - name: Run YCSB workload
      run: |
        cd build &&
        bin/ycsb-cpp load -P `spack -e . location -i ycsb`/workloads/workloada

